/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AdminToolsRouteImport } from './routes/admin-tools'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as RecipeIdRouteImport } from './routes/recipe.$id'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminToolsRoute = AdminToolsRouteImport.update({
  id: '/admin-tools',
  path: '/admin-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tools': typeof AdminToolsRoute
  '/coach': typeof CoachRoute
  '/courses': typeof CoursesRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/privacy': typeof PrivacyRoute
  '/courses/$id': typeof CoursesIdRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tools': typeof AdminToolsRoute
  '/coach': typeof CoachRoute
  '/delete-account': typeof DeleteAccountRoute
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/privacy': typeof PrivacyRoute
  '/courses/$id': typeof CoursesIdRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-tools': typeof AdminToolsRoute
  '/coach': typeof CoachRoute
  '/courses': typeof CoursesRouteWithChildren
  '/delete-account': typeof DeleteAccountRoute
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/privacy': typeof PrivacyRoute
  '/courses/$id': typeof CoursesIdRoute
  '/recipe/$id': typeof RecipeIdRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-tools'
    | '/coach'
    | '/courses'
    | '/delete-account'
    | '/grocery'
    | '/login'
    | '/planner'
    | '/privacy'
    | '/courses/$id'
    | '/recipe/$id'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-tools'
    | '/coach'
    | '/delete-account'
    | '/grocery'
    | '/login'
    | '/planner'
    | '/privacy'
    | '/courses/$id'
    | '/recipe/$id'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-tools'
    | '/coach'
    | '/courses'
    | '/delete-account'
    | '/grocery'
    | '/login'
    | '/planner'
    | '/privacy'
    | '/courses/$id'
    | '/recipe/$id'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminToolsRoute: typeof AdminToolsRoute
  CoachRoute: typeof CoachRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DeleteAccountRoute: typeof DeleteAccountRoute
  GroceryRoute: typeof GroceryRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  PrivacyRoute: typeof PrivacyRoute
  RecipeIdRoute: typeof RecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tools': {
      id: '/admin-tools'
      path: '/admin-tools'
      fullPath: '/admin-tools'
      preLoaderRoute: typeof AdminToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIdRoute: CoursesIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminToolsRoute: AdminToolsRoute,
  CoachRoute: CoachRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DeleteAccountRoute: DeleteAccountRoute,
  GroceryRoute: GroceryRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  PrivacyRoute: PrivacyRoute,
  RecipeIdRoute: RecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
