/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeIdRouteImport } from './routes/recipe.$id'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'

const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeIdRoute = RecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRouteWithChildren
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/courses/$id': typeof CoursesIdRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRouteWithChildren
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/courses/$id': typeof CoursesIdRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/courses': typeof CoursesRouteWithChildren
  '/grocery': typeof GroceryRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/courses/$id': typeof CoursesIdRoute
  '/recipe/$id': typeof RecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/grocery'
    | '/login'
    | '/planner'
    | '/courses/$id'
    | '/recipe/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/courses'
    | '/grocery'
    | '/login'
    | '/planner'
    | '/courses/$id'
    | '/recipe/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/grocery'
    | '/login'
    | '/planner'
    | '/courses/$id'
    | '/recipe/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  GroceryRoute: typeof GroceryRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  RecipeIdRoute: typeof RecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$id': {
      id: '/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/recipe/$id'
      preLoaderRoute: typeof RecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesIdRoute: typeof CoursesIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIdRoute: CoursesIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CoursesRoute: CoursesRouteWithChildren,
  GroceryRoute: GroceryRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  RecipeIdRoute: RecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
